spring.application.name=secure-cloud-storage

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Server Port
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# File upload size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Verbose Logging for Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.securecloudstorage=DEBUG
